MAX_INT = 1E9
DEFAULT_FIG_SIZE = (8,6)

class COST_FUNCTION:
    PEAK_SHIFTING_AND_HIDDEN = 'PEAK_SHIFTING_AND_HIDDEN'
    BEST_PERFORM = 'BEST_PERFORM'
    NEAREST_WEIGHT_PEAK = 'NEAREST_WEIGHT_PEAK'
    MAX_PEAK_DIS_2D = 'MAX_PEAK_DIS_2D'
    GLOBAL_PEAK_DIS_2D = 'GLOBAL_PEAK_DIS_2D'
    GLOBAL_AREA_DIFF = 'GLOBAL_AREA_DIFF'
    GLOBAL_AVG_PEAK = 'GLOBAL_AVG_PEAK'
    NEAREST_AVG_PEAK = 'NEAREST_AVG_PEAK'